language: cpp
os: linux
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-6
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    # GTest
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev
    - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - sudo tar xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    # CMake
    - mkdir $HOME/usr
    - cd $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
    - chmod +x cmake-3.7.2-Linux-x86_64.sh
    - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    - cmake --version

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake .
    - cmake --build . --target all
    - export CTEST_OUTPUT_ON_FAILURE=1
    - cmake --build . --target test
