language: cpp
os: linux
dist: trusty
sudo: required

notifications:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - g++-6
            - lcov
            - libgtkmm-3.0-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
    - eval "${MATRIX_EVAL}"
    # Bison 3.0.4
    - wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
    - mkdir $HOME/bison
    - tar -xf bison-3.0.4.tar.gz; cd bison-3.0.4; ./configure --prefix=$HOME/bison; make -j 4 install; cd $PWD/..;
    - export PATH=$HOME/bison/bin:$PATH
    - bison --version
    # GTest and GMock
    - sudo apt-get -qq update
    - sudo apt-get install -y libgtest-dev
    - sudo wget -O gtest.tar.gz https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - sudo wget -O gmock.tar.gz https://github.com/google/googlemock/archive/release-1.7.0.tar.gz
    - sudo tar xf gtest.tar.gz
    - sudo tar xf gmock.tar.gz
    - sudo mv googletest-release-1.7.0 gtest
    - cd googlemock-release-1.7.0
    - sudo cmake .
    - sudo make
    - sudo cp -a include/gmock /usr/include
    - sudo cp -a libgmock_main.a libgmock.a /usr/lib/
    - cd ../gtest/
    - sudo cmake .
    - sudo make
    - sudo cp -a ../gtest/include/gtest /usr/include
    - sudo cp -a libgtest_main.a libgtest.a /usr/lib/
    # CMake
    - mkdir $HOME/usr
    - cd $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
    - chmod +x cmake-3.7.2-Linux-x86_64.sh
    - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    - cmake --version

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake .
    - cmake --build . --target all
    - export CTEST_OUTPUT_ON_FAILURE=1
    - cmake --build . --target test
